"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = '''[sergio](garnet)@[$hostname](bold sea)$character 
$directory'''
palette = 'custom'

[character]
format = '''[       ](bold custom_orange) '''

[directory]
disabled = false
home_symbol = '/home/sergio'
format = '[current_dir:](cyan) [$path]($style)[$read_only]($read_only_style) '
style = 'bold green'

[hostname]
ssh_only = false
format = "$hostname"
style = "bold fg:10"
disabled = false

[palettes.custom]
garnet = '#b16286'
sea = '#458588'
custom_orange = '#d79921'

[package]
disabled = true
